// resources/js/sparen/components/AddRuleModal.tsx
import React, { useState, useEffect, useMemo } from "react";
import { X, Sliders } from "lucide-react";
import { Rule, BudgetCategoryGroup, BudgetType, BudgetItem, CategoryDefinition, Transaction } from "../types";
import { matchingUnlinkedTransactions } from "../matchRule";

interface AddRuleModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAdd: (rule: Omit<Rule, "id" | "matchedCount">) => void;
  initialKeyword?: string;
  initialGroup?: BudgetCategoryGroup;
  initialBudgetItemId?: string;
  budgetItems?: BudgetItem[];
  categories?: CategoryDefinition[];
  transactions?: Transaction[];
}

export const AddRuleModal: React.FC<AddRuleModalProps> = ({
  isOpen,
  onClose,
  onAdd,
  initialKeyword = "",
  initialGroup = "Dagelijks Leven",
  initialBudgetItemId = "",
  budgetItems = [],
  categories = [],
  transactions = [],
}) => {
  const [name, setName] = useState(initialKeyword ? `Regel: ${initialKeyword}` : "");
  const [keyword, setKeyword] = useState(initialKeyword);
  const [targetGroup, setTargetGroup] = useState<BudgetCategoryGroup>(initialGroup);
  const [targetBudgetItemId, setTargetBudgetItemId] = useState<string>(initialBudgetItemId);
  const [targetType, setTargetType] = useState<BudgetType>("uitgaven");
  const [matchField, setMatchField] = useState<"description" | "counterparty" | "both">("description");

  useEffect(() => {
    if (isOpen) {
      setName(initialKeyword ? `Regel: ${initialKeyword}` : "");
      setKeyword(initialKeyword);
      setTargetGroup(initialGroup);
      setTargetBudgetItemId(initialBudgetItemId);

      const catMatch = categories.find((c) => c.name === initialGroup);
      if (catMatch) {
        setTargetType(catMatch.type);
      } else if (initialGroup === "Inkomsten") {
        setTargetType("inkomsten");
      } else if (initialGroup === "Spaargeld") {
        setTargetType("sparen");
      } else {
        setTargetType("uitgaven");
      }
    }
  }, [isOpen, initialKeyword, initialGroup, initialBudgetItemId, categories]);

  const extraMatches = useMemo(
    () => matchingUnlinkedTransactions(transactions, keyword, matchField),
    [transactions, keyword, matchField]
  );

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim() || !keyword.trim()) return;

    onAdd({
      name: name.trim(),
      keyword: keyword.trim(),
      matchField,
      targetGroup,
      targetBudgetItemId: targetBudgetItemId || undefined,
      targetType,
      isActive: true,
    });

    onClose();
  };

  const handleGroupChange = (grp: BudgetCategoryGroup) => {
    setTargetGroup(grp);
    const catMatch = categories.find((c) => c.name === grp);
    if (catMatch) {
      setTargetType(catMatch.type);
    } else if (grp === "Inkomsten") {
      setTargetType("inkomsten");
    } else if (grp === "Spaargeld") {
      setTargetType("sparen");
    } else {
      setTargetType("uitgaven");
    }

    // Pick first item in new group
    const itemsInGrp = budgetItems.filter((i) => i.group === grp);
    if (itemsInGrp.length > 0) {
      setTargetBudgetItemId(itemsInGrp[0].id);
    } else {
      setTargetBudgetItemId("");
    }
  };

  const availableGroups: BudgetCategoryGroup[] = categories.length > 0
    ? categories.map((c) => c.name)
    : [
        "Inkomsten",
        "Woning",
        "Dagelijks Leven",
        "Vervoersmiddelen",
        "Verzekeringen",
        "Spaargeld",
        "Leningen",
        "Overige Vaste Kosten",
        "Overige Kosten",
      ];

  const itemsInSelectedGroup = budgetItems.filter((i) => i.group === targetGroup);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm animate-in fade-in">
      <div className="bg-slate-900 border border-slate-800 w-full max-w-md rounded-2xl shadow-2xl overflow-hidden">
        <div className="bg-slate-850 px-5 py-4 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sliders className="w-4 h-4 text-indigo-400" />
            <h3 className="font-bold text-white text-base">Nieuwe Koppelregel Aanmaken</h3>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-white p-1 rounded-lg">
            <X className="w-4 h-4" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-5 space-y-4 text-xs">
          <div>
            <label className="block text-slate-300 font-semibold mb-1">Naam van de Regel</label>
            <input
              type="text"
              required
              placeholder="Bijv. Jumbo Supermarkt of Spotify"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3.5 py-2 text-white placeholder-slate-400 focus:outline-none focus:border-indigo-500"
            />
          </div>

          <div>
            <label className="block text-slate-300 font-semibold mb-1">Trefwoord om op te filteren</label>
            <input
              type="text"
              required
              placeholder="Bijv. JUMBO, Spotify, Dirk, Kruidvat..."
              value={keyword}
              onChange={(e) => setKeyword(e.target.value)}
              className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3.5 py-2 text-white font-mono placeholder-slate-400 focus:outline-none focus:border-indigo-500"
            />
            {keyword.trim().length < 2 ? (
              <p className="text-[10px] text-slate-400 mt-1">
                Typ minstens 2 tekens om te zien welke ongekoppelde rijen meegaan.
              </p>
            ) : (
              <div className="mt-2 bg-indigo-950/40 border border-indigo-800/50 rounded-lg p-2.5 space-y-1.5">
                <p className="text-[11px] text-indigo-200 font-semibold">
                  {extraMatches.length === 0
                    ? "Geen ongekoppelde rijen voldoen aan dit trefwoord."
                    : `${extraMatches.length} ongekoppelde ${extraMatches.length === 1 ? "rij wordt" : "rijen worden"} nu ook gekoppeld.`}
                </p>
                {extraMatches.length > 0 && (
                  <ul className="space-y-1">
                    {extraMatches.slice(0, 4).map((tx) => (
                      <li key={tx.id} className="text-[10px] text-slate-400 truncate">
                        {tx.date} · {tx.description}
                      </li>
                    ))}
                    {extraMatches.length > 4 && (
                      <li className="text-[10px] text-slate-500">+ {extraMatches.length - 4} meer</li>
                    )}
                  </ul>
                )}
              </div>
            )}
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="block text-slate-300 font-semibold mb-1">Doel Categorie (Rubriek)</label>
              <select
                value={targetGroup}
                onChange={(e) => handleGroupChange(e.target.value as BudgetCategoryGroup)}
                className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-white focus:outline-none focus:border-indigo-500 cursor-pointer"
              >
                {availableGroups.map((g) => (
                  <option key={g} value={g}>
                    {g}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-slate-300 font-semibold mb-1">Specifieke Begrotingspost</label>
              <select
                value={targetBudgetItemId}
                onChange={(e) => setTargetBudgetItemId(e.target.value)}
                className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-white focus:outline-none focus:border-indigo-500 cursor-pointer"
              >
                <option value="">(Geen specifieke post)</option>
                {itemsInSelectedGroup.map((item) => (
                  <option key={item.id} value={item.id}>
                    {item.name}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div>
            <label className="block text-slate-300 font-semibold mb-1">Zoekveld</label>
            <select
              value={matchField}
              onChange={(e) => setMatchField(e.target.value as any)}
              className="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-white focus:outline-none focus:border-indigo-500 cursor-pointer"
            >
              <option value="description">Omschrijving van transactie</option>
              <option value="counterparty">Naam van tegenpartij</option>
              <option value="both">Zowel omschrijving als tegenpartij</option>
            </select>
          </div>

          <div className="pt-3 border-t border-slate-800 flex justify-end gap-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl font-medium transition-colors"
            >
              Annuleren
            </button>
            <button
              type="submit"
              className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold rounded-xl transition-colors shadow-md shadow-indigo-600/20"
            >
              {extraMatches.length > 0
                ? `Opslaan & ${extraMatches.length} rijen koppelen`
                : "Koppelregel Opslaan"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

// resources/js/sparen/components/AddRuleModal.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { X, Sliders } from "lucide-vue-next";
import type {
  Rule,
  BudgetCategoryGroup,
  BudgetType,
  BudgetItem,
  CategoryDefinition,
  Transaction,
} from "../types";
import { matchingUnlinkedTransactions } from "../matchRule";

const props = withDefaults(
  defineProps<{
    isOpen: boolean;
    onClose: () => void;
    onAdd: (rule: Omit<Rule, "id" | "matchedCount">) => void;
    initialKeyword?: string;
    initialGroup?: BudgetCategoryGroup;
    initialBudgetItemId?: string;
    budgetItems?: BudgetItem[];
    categories?: CategoryDefinition[];
    transactions?: Transaction[];
  }>(),
  {
    initialKeyword: "",
    initialGroup: "Dagelijks Leven",
    initialBudgetItemId: "",
    budgetItems: () => [],
    categories: () => [],
    transactions: () => [],
  }
);

const name = ref("");
const keyword = ref("");
const targetGroup = ref<BudgetCategoryGroup>("Dagelijks Leven");
const targetBudgetItemId = ref("");
const targetType = ref<BudgetType>("uitgaven");
const matchField = ref<"description" | "counterparty" | "both">("description");

watch(
  () =>
    [
      props.isOpen,
      props.initialKeyword,
      props.initialGroup,
      props.initialBudgetItemId,
      props.categories,
    ] as const,
  () => {
    if (!props.isOpen) return;
    name.value = props.initialKeyword ? `Regel: ${props.initialKeyword}` : "";
    keyword.value = props.initialKeyword;
    targetGroup.value = props.initialGroup;
    targetBudgetItemId.value = props.initialBudgetItemId;

    const catMatch = props.categories.find((c) => c.name === props.initialGroup);
    if (catMatch) {
      targetType.value = catMatch.type;
    } else if (props.initialGroup === "Inkomsten") {
      targetType.value = "inkomsten";
    } else if (props.initialGroup === "Spaargeld") {
      targetType.value = "sparen";
    } else {
      targetType.value = "uitgaven";
    }
  }
);

const extraMatches = computed(() =>
  matchingUnlinkedTransactions(props.transactions, keyword.value, matchField.value)
);

const availableGroups = computed(() =>
  props.categories.length > 0
    ? props.categories.map((c) => c.name)
    : [
        "Inkomsten",
        "Woning",
        "Dagelijks Leven",
        "Vervoersmiddelen",
        "Verzekeringen",
        "Spaargeld",
        "Leningen",
        "Overige Vaste Kosten",
        "Overige Kosten",
      ]
);

const itemsInSelectedGroup = computed(() =>
  props.budgetItems.filter((i) => i.group === targetGroup.value)
);

function handleGroupChange(grp: BudgetCategoryGroup) {
  targetGroup.value = grp;
  const catMatch = props.categories.find((c) => c.name === grp);
  if (catMatch) {
    targetType.value = catMatch.type;
  } else if (grp === "Inkomsten") {
    targetType.value = "inkomsten";
  } else if (grp === "Spaargeld") {
    targetType.value = "sparen";
  } else {
    targetType.value = "uitgaven";
  }

  const itemsInGrp = props.budgetItems.filter((i) => i.group === grp);
  targetBudgetItemId.value = itemsInGrp.length > 0 ? itemsInGrp[0].id : "";
}

function handleSubmit() {
  if (!name.value.trim() || !keyword.value.trim()) return;

  props.onAdd({
    name: name.value.trim(),
    keyword: keyword.value.trim(),
    matchField: matchField.value,
    targetGroup: targetGroup.value,
    targetBudgetItemId: targetBudgetItemId.value || undefined,
    targetType: targetType.value,
    isActive: true,
  });

  props.onClose();
}
</script>

<template>
  <div
    v-if="isOpen"
    class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm animate-in fade-in"
  >
    <div class="bg-slate-900 border border-slate-800 w-full max-w-md rounded-2xl shadow-2xl overflow-hidden">
      <div class="bg-slate-850 px-5 py-4 border-b border-slate-800 flex items-center justify-between">
        <div class="flex items-center gap-2">
          <Sliders class="w-4 h-4 text-indigo-400" />
          <h3 class="font-bold text-white text-base">Nieuwe Koppelregel Aanmaken</h3>
        </div>
        <button type="button" class="text-slate-400 hover:text-white p-1 rounded-lg" @click="onClose">
          <X class="w-4 h-4" />
        </button>
      </div>

      <form class="p-5 space-y-4 text-xs" @submit.prevent="handleSubmit">
        <div>
          <label class="block text-slate-300 font-semibold mb-1">Naam van de Regel</label>
          <input
            v-model="name"
            type="text"
            required
            placeholder="Bijv. Jumbo Supermarkt of Spotify"
            class="w-full bg-slate-800 border border-slate-700 rounded-xl px-3.5 py-2 text-white placeholder-slate-400 focus:outline-none focus:border-indigo-500"
          />
        </div>

        <div>
          <label class="block text-slate-300 font-semibold mb-1">Trefwoord om op te filteren</label>
          <input
            v-model="keyword"
            type="text"
            required
            placeholder="Bijv. JUMBO, Spotify, Dirk, Kruidvat..."
            class="w-full bg-slate-800 border border-slate-700 rounded-xl px-3.5 py-2 text-white font-mono placeholder-slate-400 focus:outline-none focus:border-indigo-500"
          />
          <p v-if="keyword.trim().length < 2" class="text-[10px] text-slate-400 mt-1">
            Typ minstens 2 tekens om te zien welke ongekoppelde rijen meegaan.
          </p>
          <div v-else class="mt-2 bg-indigo-950/40 border border-indigo-800/50 rounded-lg p-2.5 space-y-1.5">
            <p class="text-[11px] text-indigo-200 font-semibold">
              {{
                extraMatches.length === 0
                  ? "Geen ongekoppelde rijen voldoen aan dit trefwoord."
                  : `${extraMatches.length} ongekoppelde ${extraMatches.length === 1 ? "rij wordt" : "rijen worden"} nu ook gekoppeld.`
              }}
            </p>
            <ul v-if="extraMatches.length > 0" class="space-y-1">
              <li
                v-for="tx in extraMatches.slice(0, 4)"
                :key="tx.id"
                class="text-[10px] text-slate-400 truncate"
              >
                {{ tx.date }} · {{ tx.description }}
              </li>
              <li v-if="extraMatches.length > 4" class="text-[10px] text-slate-500">
                + {{ extraMatches.length - 4 }} meer
              </li>
            </ul>
          </div>
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div>
            <label class="block text-slate-300 font-semibold mb-1">Doel Categorie (Rubriek)</label>
            <select
              :value="targetGroup"
              class="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-white focus:outline-none focus:border-indigo-500 cursor-pointer"
              @change="handleGroupChange(($event.target as HTMLSelectElement).value)"
            >
              <option v-for="g in availableGroups" :key="g" :value="g">{{ g }}</option>
            </select>
          </div>

          <div>
            <label class="block text-slate-300 font-semibold mb-1">Specifieke Begrotingspost</label>
            <select
              v-model="targetBudgetItemId"
              class="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-white focus:outline-none focus:border-indigo-500 cursor-pointer"
            >
              <option value="">(Geen specifieke post)</option>
              <option v-for="item in itemsInSelectedGroup" :key="item.id" :value="item.id">
                {{ item.name }}
              </option>
            </select>
          </div>
        </div>

        <div>
          <label class="block text-slate-300 font-semibold mb-1">Zoekveld</label>
          <select
            v-model="matchField"
            class="w-full bg-slate-800 border border-slate-700 rounded-xl px-3 py-2 text-white focus:outline-none focus:border-indigo-500 cursor-pointer"
          >
            <option value="description">Omschrijving van transactie</option>
            <option value="counterparty">Naam van tegenpartij</option>
            <option value="both">Zowel omschrijving als tegenpartij</option>
          </select>
        </div>

        <div class="pt-3 border-t border-slate-800 flex justify-end gap-2">
          <button
            type="button"
            class="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl font-medium transition-colors"
            @click="onClose"
          >
            Annuleren
          </button>
          <button
            type="submit"
            class="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold rounded-xl transition-colors shadow-md shadow-indigo-600/20"
          >
            {{
              extraMatches.length > 0
                ? `Opslaan & ${extraMatches.length} rijen koppelen`
                : "Koppelregel Opslaan"
            }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
